# frozen_string_literal: true
source :rubygems
gem 'rack', '<2.0'
gem 'sinatra'
gem 'sinatra-flash'
gem 'pony'
gem 'slim'
gem 'sass'
gem 'dm-core'
gem 'dm-migrations'
gem 'thin'
gem 'pg', :group => :production
gem 'dm-postgres-adapter', :group => :production
gem 'dm-sqlite-adapter', :group => :development
gem 'coffee-script'
gem 'therubyracer'
